### ISSUE TITLE
[Feature] Custom endpoint URL

### ISSUE THREAD

**Issue by RedHooman** [sfortis/openai_tts#16]
Hello,

I'm trying to get https://github.com/ther3zz/TTS working with home assistant (specifically this fork, as it supports multi-speaker models/xTTSv2). I've spent hours trying to bodge MaryTTS to work with this, but it has not been successful and I've given up trying (even tried making a proxy via a PHP Laravel app, but MaryTTS seems broken and isn't POSTing the actual text field?)

I was wondering if openai_tts could be modified to provide the option to specify a custom host that provides an OpenAI compatible endpoint. Alternatively, how much work would it be to create a separate project specifically for Coqui TTS? I'd be willing to donate for getting this working as I want all my AI running locally. I pretty much just want to be able to point HA to Coqui TTS -> Give it the endpoint URL and speaker settings -> Have it work.

This is how I've been running the forked TTS:

docker-compose.yml

```
    coqui-ai-tts:
        build: ./TTS
        container_name: tts
        restart: no
        environment:
            - COQUI_TOS_AGREED=1
        # To run the model, use the below entrypoint
        entrypoint: /bin/bash -c 'python3 TTS/server/server.py --list_models && python3 TTS/server/server.py --model_path /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/model.pth --config_path /root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/config.json --use_cuda true'
        
        # To download the model, use the below entrypoint
        #entrypoint: /bin/bash -c 'python3 TTS/server/server.py --list_models && python3 TTS/server/server.py --model_name tts_models/multilingual/multi-dataset/xtts_v2 --use_cuda true'
        volumes:
            - ./volumes/tts_models:/app/tts_models
            - ./volumes/tts:/root/.local/share/tts
        ports:
            - 5002:5002
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          device_ids: ['0']
                          capabilities: [gpu]
```

Once the TTS server has been started, a request to the server has the following parameters:

```
GET /api/tts?text=SOMETEXTHERE&speaker_id=Claribel%20Dervla&style_wav=&language_id=en
```

Parameters:

```
text
speaker_id
style_wav
language_id
```

I don't think there is an API endpoint to return the list of supported languages or speakers, but perhaps as a temporary means, this can be manually specified until an endpoint is added upstream?

Thanks!
