### ISSUE TITLE
Unable to use environment variable

### ISSUE THREAD

**Issue by codysaylor** [sfortis/openai_tts#3]
Hi, first I want to say great job on this and thank you for making it!

One small issue I found though that I was wondering if you could look into: the configuration.yaml file is not happy with me using environment variables for the API key.

Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: OPENAIAPI

This seems to work with other items in the configuration.yaml file so I assume it's related to the integration, but might not be.

```yaml
tts:
  - platform: openai_tts
    api_key: !env_var OPENAIAPI
```
