### ISSUE TITLE
Invalid options found: ['chime', 'instructions']

### ISSUE THREAD

**Issue by brix29** [sfortis/openai_tts#31]
Hi sfortis,

Thank you very much for this great integration. So many possibilities! :-)

Somehow I get an error message, when using the "options":

` **Invalid options found: ['chime', 'instructions']**`

```
target:
  entity_id: tts.openai_tts_tts_1
data:
  cache: true
  media_player_entity_id: media_player.bedroom_speaker
  message: My speech has improved now!
  options:
    chime: true
    instructions: Speak like a pirate
action: tts.speak
```

I'm running the latest version of your integration. 

Any idea how I could fix it?
Do you plan to integrate "instructions" to the "configuration" so "instructions" can be used together with Assist?

Thank you very much!

Best,
Brix
