### ISSUE TITLE
Add Chime Name Option

### ISSUE THREAD

**Issue by qJake** [sfortis/openai_tts#34]
Right [here](https://github.com/sfortis/openai_tts/blob/6478068c6df6f10e6aaa96c4417460f4f5bb7911/custom_components/openai_tts/tts.py#L70):

```py
    @property
    def supported_options(self) -> list:
        return ["instructions", "chime"]
```

It would be awesome if in addition to `chime`, we had support for `chime_name`, so you could do silly stuff like:

```yaml
data:
  message: Oh no! Everything is going wrong all at once!
  media_player_entity_id: media_player.sample
  options:
    chime: true
    chime_name: Siren # This would already exist in the chimes folder and be a valid dropdown option on the config page
```
