### ISSUE TITLE
Unable to produce TTS output

### ISSUE THREAD

**Issue by nimroddolev** [sfortis/openai_tts#6]
I have added my OpenAI API key in the configuration, however whenever I try to call the `tts.openai_tts_say`, for example:

```
service: tts.openai_tts_say
data:
  entity_id: media_player.living_room_speaker
  message: This is a test message
```

I receive the following error:

```
HTTP error from OpenAI: 429 Client Error: Too Many Requests for url: https://api.openai.com/v1/audio/speech
```

I haven't seen any other steps to take in order to start using the service. Any idea on what the issue might be?
